// cspell:disable
import {getObjectTypedKeys} from '@augment-vir/common';

/**
 * Generated by `npm run init` from the files in `./molecules/`. Do not edit by hand.
 *
 * Display order: like a Pokédex, each molecule is followed by its evolution line. Molecules that
 * start a line are ordered by fewest atoms first, ties broken by total bond order, then by route
 * name.
 */
export const moleculeSummaries: Readonly<
    Record<string, Readonly<{name: string; formula: string; evolvesInto: string[]}>>
> = {
    bromine: {
        name: 'Bromine',
        formula: 'Br₂',
        evolvesInto: ['halothane'],
    },
    halothane: {
        name: 'Halothane',
        formula: 'BrClF₃C₂H',
        evolvesInto: [],
    },
    chlorine: {
        name: 'Chlorine',
        formula: 'Cl₂',
        evolvesInto: [
            'chloral-hydrate',
            'hypochlorous-acid',
        ],
    },
    'hypochlorous-acid': {
        name: 'Hypochlorous Acid',
        formula: 'ClOH',
        evolvesInto: [],
    },
    'chloral-hydrate': {
        name: 'Chloral Hydrate',
        formula: 'Cl₃O₂C₂H₃',
        evolvesInto: ['ddt'],
    },
    ddt: {
        name: 'DDT',
        formula: 'Cl₅C₁₄H₉',
        evolvesInto: [],
    },
    hydrogen: {
        name: 'Hydrogen',
        formula: 'H₂',
        evolvesInto: ['water'],
    },
    water: {
        name: 'Water',
        formula: 'H₂O',
        evolvesInto: ['hydrogen-peroxide'],
    },
    'hydrogen-peroxide': {
        name: 'Hydrogen Peroxide',
        formula: 'H₂O₂',
        evolvesInto: [],
    },
    'hydrogen-chloride': {
        name: 'Hydrogen Chloride',
        formula: 'HCl',
        evolvesInto: [],
    },
    'hydrogen-fluoride': {
        name: 'Hydrogen Fluoride',
        formula: 'FH',
        evolvesInto: [
            'boron-trifluoride',
            'dichlorodifluoromethane',
        ],
    },
    'boron-trifluoride': {
        name: 'Boron Trifluoride',
        formula: 'BF₃',
        evolvesInto: [],
    },
    dichlorodifluoromethane: {
        name: 'Dichlorodifluoromethane',
        formula: 'Cl₂F₂C',
        evolvesInto: [],
    },
    iodine: {
        name: 'Iodine',
        formula: 'I₂',
        evolvesInto: [
            'iodoform',
            'thyroxine',
        ],
    },
    iodoform: {
        name: 'Iodoform',
        formula: 'I₃CH',
        evolvesInto: [],
    },
    thyroxine: {
        name: 'Thyroxine',
        formula: 'I₄O₄NC₁₅H₁₁',
        evolvesInto: [],
    },
    oxygen: {
        name: 'Oxygen',
        formula: 'O₂',
        evolvesInto: ['ozone'],
    },
    ozone: {
        name: 'Ozone',
        formula: 'O₃',
        evolvesInto: [],
    },
    'carbon-monoxide': {
        name: 'Carbon Monoxide',
        formula: 'CO',
        evolvesInto: [
            'carbon-dioxide',
            'phosgene',
        ],
    },
    'carbon-dioxide': {
        name: 'Carbon Dioxide',
        formula: 'CO₂',
        evolvesInto: ['carbonic-acid'],
    },
    'carbonic-acid': {
        name: 'Carbonic Acid',
        formula: 'O₃CH₂',
        evolvesInto: [],
    },
    phosgene: {
        name: 'Phosgene',
        formula: 'Cl₂OC',
        evolvesInto: [],
    },
    nitrogen: {
        name: 'Nitrogen',
        formula: 'N₂',
        evolvesInto: ['ammonia'],
    },
    ammonia: {
        name: 'Ammonia',
        formula: 'NH₃',
        evolvesInto: [
            'hydrazine',
            'urea',
        ],
    },
    hydrazine: {
        name: 'Hydrazine',
        formula: 'N₂H₄',
        evolvesInto: [],
    },
    urea: {
        name: 'Urea',
        formula: 'ON₂CH₄',
        evolvesInto: [],
    },
    'hydrogen-sulfide': {
        name: 'Hydrogen Sulfide',
        formula: 'SH₂',
        evolvesInto: [
            'octasulfur',
            'ethanethiol',
        ],
    },
    octasulfur: {
        name: 'Octasulfur',
        formula: 'S₈',
        evolvesInto: [],
    },
    ethanethiol: {
        name: 'Ethanethiol',
        formula: 'SC₂H₆',
        evolvesInto: [],
    },
    'xenon-difluoride': {
        name: 'Xenon Difluoride',
        formula: 'XeF₂',
        evolvesInto: ['xenon-tetrafluoride'],
    },
    'xenon-tetrafluoride': {
        name: 'Xenon Tetrafluoride',
        formula: 'XeF₄',
        evolvesInto: [],
    },
    'hydrogen-cyanide': {
        name: 'Hydrogen Cyanide',
        formula: 'NCH',
        evolvesInto: [
            'glycine',
            'edta',
        ],
    },
    glycine: {
        name: 'Glycine',
        formula: 'O₂NC₂H₅',
        evolvesInto: [
            'creatine',
            'glyphosate',
        ],
    },
    creatine: {
        name: 'Creatine',
        formula: 'O₂N₃C₄H₉',
        evolvesInto: [],
    },
    glyphosate: {
        name: 'Glyphosate',
        formula: 'PO₅NC₃H₈',
        evolvesInto: [],
    },
    edta: {
        name: 'EDTA',
        formula: 'O₈N₂C₁₀H₁₆',
        evolvesInto: [],
    },
    'nitrous-oxide': {
        name: 'Nitrous Oxide',
        formula: 'ON₂',
        evolvesInto: [],
    },
    'sulfur-dioxide': {
        name: 'Sulfur Dioxide',
        formula: 'SO₂',
        evolvesInto: [
            'sulfur-trioxide',
            'thionyl-chloride',
        ],
    },
    'thionyl-chloride': {
        name: 'Thionyl Chloride',
        formula: 'Cl₂SO',
        evolvesInto: [],
    },
    'sulfur-trioxide': {
        name: 'Sulfur Trioxide',
        formula: 'SO₃',
        evolvesInto: [
            'sulfamic-acid',
            'sulfuric-acid',
        ],
    },
    'sulfuric-acid': {
        name: 'Sulfuric Acid',
        formula: 'SO₄H₂',
        evolvesInto: [],
    },
    'sulfamic-acid': {
        name: 'Sulfamic Acid',
        formula: 'SO₃NH₃',
        evolvesInto: [],
    },
    'nitrogen-trifluoride': {
        name: 'Nitrogen Trifluoride',
        formula: 'F₃N',
        evolvesInto: [],
    },
    phosphine: {
        name: 'Phosphine',
        formula: 'PH₃',
        evolvesInto: [],
    },
    'phosphorus-trichloride': {
        name: 'Phosphorus Trichloride',
        formula: 'Cl₃P',
        evolvesInto: ['phosphorus-pentachloride'],
    },
    'phosphorus-pentachloride': {
        name: 'Phosphorus Pentachloride',
        formula: 'PCl₅',
        evolvesInto: ['phosphoric-acid'],
    },
    'phosphoric-acid': {
        name: 'Phosphoric Acid',
        formula: 'PO₄H₃',
        evolvesInto: [],
    },
    formaldehyde: {
        name: 'Formaldehyde',
        formula: 'CH₂O',
        evolvesInto: [
            'formic-acid',
            'methenamine',
        ],
    },
    'formic-acid': {
        name: 'Formic Acid',
        formula: 'O₂CH₂',
        evolvesInto: [],
    },
    methenamine: {
        name: 'Methenamine',
        formula: 'N₄C₆H₁₂',
        evolvesInto: [],
    },
    acetylene: {
        name: 'Acetylene',
        formula: 'C₂H₂',
        evolvesInto: ['acetaldehyde'],
    },
    acetaldehyde: {
        name: 'Acetaldehyde',
        formula: 'OC₂H₄',
        evolvesInto: ['acetic-acid'],
    },
    'acetic-acid': {
        name: 'Acetic Acid',
        formula: 'C₂H₄O₂',
        evolvesInto: [],
    },
    'white-phosphorus': {
        name: 'White Phosphorus',
        formula: 'P₄',
        evolvesInto: [],
    },
    'carbon-tetrachloride': {
        name: 'Carbon Tetrachloride',
        formula: 'Cl₄C',
        evolvesInto: [],
    },
    chloroform: {
        name: 'Chloroform',
        formula: 'Cl₃CH',
        evolvesInto: ['tetrafluoroethylene'],
    },
    tetrafluoroethylene: {
        name: 'Tetrafluoroethylene',
        formula: 'F₄C₂',
        evolvesInto: ['pfoa'],
    },
    pfoa: {
        name: 'PFOA',
        formula: 'F₁₅O₂C₈H',
        evolvesInto: [],
    },
    hydroxylamine: {
        name: 'Hydroxylamine',
        formula: 'ONH₃',
        evolvesInto: [],
    },
    methane: {
        name: 'Methane',
        formula: 'CH₄',
        evolvesInto: ['methanol'],
    },
    methanol: {
        name: 'Methanol',
        formula: 'OCH₄',
        evolvesInto: [
            'aspartame',
            'trimethylamine',
        ],
    },
    trimethylamine: {
        name: 'Trimethylamine',
        formula: 'NC₃H₉',
        evolvesInto: [],
    },
    aspartame: {
        name: 'Aspartame',
        formula: 'O₅N₂C₁₄H₁₈',
        evolvesInto: [],
    },
    silane: {
        name: 'Silane',
        formula: 'SiH₄',
        evolvesInto: [],
    },
    'silicon-tetrachloride': {
        name: 'Silicon Tetrachloride',
        formula: 'Cl₄Si',
        evolvesInto: [],
    },
    tetrafluoromethane: {
        name: 'Tetrafluoromethane',
        formula: 'F₄C',
        evolvesInto: [],
    },
    'nitric-acid': {
        name: 'Nitric Acid',
        formula: 'O₃NH',
        evolvesInto: [
            'tnt',
            'nitromethane',
        ],
    },
    nitromethane: {
        name: 'Nitromethane',
        formula: 'O₂NCH₃',
        evolvesInto: [],
    },
    tnt: {
        name: 'TNT',
        formula: 'O₆N₃C₇H₅',
        evolvesInto: [],
    },
    ethylene: {
        name: 'Ethylene',
        formula: 'C₂H₄',
        evolvesInto: [
            'ethanol',
            'ethylene-glycol',
        ],
    },
    ethanol: {
        name: 'Ethanol',
        formula: 'C₂H₆O',
        evolvesInto: ['diethyl-ether'],
    },
    'diethyl-ether': {
        name: 'Diethyl Ether',
        formula: 'OC₄H₁₀',
        evolvesInto: [],
    },
    'ethylene-glycol': {
        name: 'Ethylene Glycol',
        formula: 'O₂C₂H₆',
        evolvesInto: ['18-crown-6'],
    },
    '18-crown-6': {
        name: '18-Crown-6',
        formula: 'O₆C₁₂H₂₄',
        evolvesInto: [],
    },
    'dinitrogen-tetroxide': {
        name: 'Dinitrogen Tetroxide',
        formula: 'O₄N₂',
        evolvesInto: [],
    },
    'boric-acid': {
        name: 'Boric Acid',
        formula: 'BO₃H₃',
        evolvesInto: [],
    },
    'sulfur-hexafluoride': {
        name: 'Sulfur Hexafluoride',
        formula: 'SF₆',
        evolvesInto: [],
    },
    diborane: {
        name: 'Diborane',
        formula: 'B₂H₆',
        evolvesInto: ['borazine'],
    },
    borazine: {
        name: 'Borazine',
        formula: 'B₃N₃H₆',
        evolvesInto: [],
    },
    'dimethyl-sulfide': {
        name: 'Dimethyl Sulfide',
        formula: 'SC₂H₆',
        evolvesInto: ['dimethyl-sulfoxide'],
    },
    'dimethyl-sulfoxide': {
        name: 'Dimethyl Sulfoxide',
        formula: 'SOC₂H₆',
        evolvesInto: [],
    },
    cyclopropane: {
        name: 'Cyclopropane',
        formula: 'C₃H₆',
        evolvesInto: [],
    },
    acetone: {
        name: 'Acetone',
        formula: 'OC₃H₆',
        evolvesInto: ['isopropyl-alcohol'],
    },
    'isopropyl-alcohol': {
        name: 'Isopropyl Alcohol',
        formula: 'OC₃H₈',
        evolvesInto: [],
    },
    cisplatin: {
        name: 'Cisplatin',
        formula: 'PtCl₂N₂H₆',
        evolvesInto: [],
    },
    propane: {
        name: 'Propane',
        formula: 'C₃H₈',
        evolvesInto: [],
    },
    'allyl-isothiocyanate': {
        name: 'Allyl Isothiocyanate',
        formula: 'SNC₄H₅',
        evolvesInto: [],
    },
    'lactic-acid': {
        name: 'Lactic Acid',
        formula: 'O₃C₃H₆',
        evolvesInto: [],
    },
    benzene: {
        name: 'Benzene',
        formula: 'C₆H₆',
        evolvesInto: [
            'salicylic-acid',
            'acetaminophen',
        ],
    },
    'salicylic-acid': {
        name: 'Salicylic Acid',
        formula: 'O₃C₇H₆',
        evolvesInto: [
            'aspirin',
            'methyl-salicylate',
        ],
    },
    'methyl-salicylate': {
        name: 'Methyl Salicylate',
        formula: 'O₃C₈H₈',
        evolvesInto: [],
    },
    aspirin: {
        name: 'Aspirin',
        formula: 'C₉H₈O₄',
        evolvesInto: [],
    },
    acetaminophen: {
        name: 'Acetaminophen',
        formula: 'O₂NC₈H₉',
        evolvesInto: [],
    },
    'trichloroisocyanuric-acid': {
        name: 'Trichloroisocyanuric Acid',
        formula: 'Cl₃O₃N₃C₃',
        evolvesInto: [],
    },
    uracil: {
        name: 'Uracil',
        formula: 'O₂N₂C₄H₄',
        evolvesInto: [
            'cytosine',
            'thymine',
        ],
    },
    cytosine: {
        name: 'Cytosine',
        formula: 'ON₃C₄H₅',
        evolvesInto: [],
    },
    thymine: {
        name: 'Thymine',
        formula: 'O₂N₂C₅H₆',
        evolvesInto: [],
    },
    purine: {
        name: 'Purine',
        formula: 'N₄C₅H₄',
        evolvesInto: [
            'adenine',
            'guanine',
        ],
    },
    adenine: {
        name: 'Adenine',
        formula: 'N₅C₅H₅',
        evolvesInto: ['adenosine-triphosphate'],
    },
    'adenosine-triphosphate': {
        name: 'Adenosine Triphosphate',
        formula: 'P₃O₁₃N₅C₁₀H₁₆',
        evolvesInto: [],
    },
    guanine: {
        name: 'Guanine',
        formula: 'ON₅C₅H₅',
        evolvesInto: [],
    },
    butane: {
        name: 'Butane',
        formula: 'C₄H₁₀',
        evolvesInto: [],
    },
    glycerol: {
        name: 'Glycerol',
        formula: 'O₃C₃H₈',
        evolvesInto: ['nitroglycerin'],
    },
    nitroglycerin: {
        name: 'Nitroglycerin',
        formula: 'O₉N₃C₃H₅',
        evolvesInto: [],
    },
    cysteine: {
        name: 'Cysteine',
        formula: 'SO₂NC₃H₇',
        evolvesInto: ['taurine'],
    },
    taurine: {
        name: 'Taurine',
        formula: 'SO₃NC₂H₇',
        evolvesInto: [],
    },
    benzaldehyde: {
        name: 'Benzaldehyde',
        formula: 'OC₇H₆',
        evolvesInto: ['cinnamaldehyde'],
    },
    cinnamaldehyde: {
        name: 'Cinnamaldehyde',
        formula: 'OC₉H₈',
        evolvesInto: [],
    },
    niacin: {
        name: 'Niacin',
        formula: 'O₂NC₆H₅',
        evolvesInto: ['nicotine'],
    },
    nicotine: {
        name: 'Nicotine',
        formula: 'N₂C₁₀H₁₄',
        evolvesInto: [],
    },
    sevoflurane: {
        name: 'Sevoflurane',
        formula: 'F₇OC₄H₃',
        evolvesInto: [],
    },
    creatinine: {
        name: 'Creatinine',
        formula: 'ON₃C₄H₇',
        evolvesInto: [],
    },
    melamine: {
        name: 'Melamine',
        formula: 'N₆C₃H₆',
        evolvesInto: [],
    },
    acesulfame: {
        name: 'Acesulfame',
        formula: 'SO₄NC₄H₅',
        evolvesInto: [],
    },
    gaba: {
        name: 'GABA',
        formula: 'O₂NC₄H₉',
        evolvesInto: [],
    },
    'uric-acid': {
        name: 'Uric Acid',
        formula: 'O₃N₄C₅H₄',
        evolvesInto: [],
    },
    histamine: {
        name: 'Histamine',
        formula: 'N₃C₅H₉',
        evolvesInto: [],
    },
    coumarin: {
        name: 'Coumarin',
        formula: 'O₂C₉H₆',
        evolvesInto: [],
    },
    saccharin: {
        name: 'Saccharin',
        formula: 'SO₃NC₇H₅',
        evolvesInto: [],
    },
    'isoamyl-mercaptan': {
        name: 'Isoamyl Mercaptan',
        formula: 'SC₅H₁₂',
        evolvesInto: [],
    },
    'glutamic-acid': {
        name: 'Glutamic Acid',
        formula: 'O₄NC₅H₉',
        evolvesInto: [],
    },
    allicin: {
        name: 'Allicin',
        formula: 'S₂OC₆H₁₀',
        evolvesInto: [],
    },
    vanillin: {
        name: 'Vanillin',
        formula: 'O₃C₈H₈',
        evolvesInto: ['capsaicin'],
    },
    capsaicin: {
        name: 'Capsaicin',
        formula: 'O₃NC₁₈H₂₇',
        evolvesInto: [],
    },
    ninhydrin: {
        name: 'Ninhydrin',
        formula: 'O₄C₉H₆',
        evolvesInto: [],
    },
    methionine: {
        name: 'Methionine',
        formula: 'SO₂NC₅H₁₁',
        evolvesInto: [],
    },
    ribose: {
        name: 'Ribose',
        formula: 'O₅C₅H₁₀',
        evolvesInto: ['riboflavin'],
    },
    riboflavin: {
        name: 'Riboflavin',
        formula: 'O₆N₄C₁₇H₂₀',
        evolvesInto: [],
    },
    metformin: {
        name: 'Metformin',
        formula: 'N₅C₄H₁₁',
        evolvesInto: [],
    },
    'ascorbic-acid': {
        name: 'Ascorbic Acid',
        formula: 'O₆C₆H₈',
        evolvesInto: [],
    },
    'citric-acid': {
        name: 'Citric Acid',
        formula: 'O₇C₆H₈',
        evolvesInto: [],
    },
    theobromine: {
        name: 'Theobromine',
        formula: 'O₂N₄C₇H₈',
        evolvesInto: ['caffeine'],
    },
    caffeine: {
        name: 'Caffeine',
        formula: 'C₈H₁₀N₄O₂',
        evolvesInto: [],
    },
    theophylline: {
        name: 'Theophylline',
        formula: 'O₂N₄C₇H₈',
        evolvesInto: [],
    },
    dopamine: {
        name: 'Dopamine',
        formula: 'O₂NC₈H₁₁',
        evolvesInto: ['adrenaline'],
    },
    adrenaline: {
        name: 'Adrenaline',
        formula: 'O₃NC₉H₁₃',
        evolvesInto: [],
    },
    fructose: {
        name: 'Fructose',
        formula: 'O₆C₆H₁₂',
        evolvesInto: ['sucrose'],
    },
    sucrose: {
        name: 'Sucrose',
        formula: 'O₁₁C₁₂H₂₂',
        evolvesInto: [],
    },
    glucose: {
        name: 'Glucose',
        formula: 'C₆H₁₂O₆',
        evolvesInto: ['lactose'],
    },
    lactose: {
        name: 'Lactose',
        formula: 'O₁₁C₁₂H₂₂',
        evolvesInto: [],
    },
    triclosan: {
        name: 'Triclosan',
        formula: 'Cl₃O₂C₁₂H₇',
        evolvesInto: [],
    },
    carvone: {
        name: 'Carvone',
        formula: 'OC₁₀H₁₄',
        evolvesInto: [],
    },
    serotonin: {
        name: 'Serotonin',
        formula: 'ON₂C₁₀H₁₂',
        evolvesInto: ['melatonin'],
    },
    melatonin: {
        name: 'Melatonin',
        formula: 'O₂N₂C₁₃H₁₆',
        evolvesInto: [],
    },
    hydrochlorothiazide: {
        name: 'Hydrochlorothiazide',
        formula: 'ClS₂O₄N₃C₇H₈',
        evolvesInto: [],
    },
    acetylcholine: {
        name: 'Acetylcholine',
        formula: 'O₂NC₇H₁₆',
        evolvesInto: [],
    },
    limonene: {
        name: 'Limonene',
        formula: 'C₁₀H₁₆',
        evolvesInto: [],
    },
    luciferin: {
        name: 'Luciferin',
        formula: 'S₂O₃N₂C₁₁H₈',
        evolvesInto: [],
    },
    tryptophan: {
        name: 'Tryptophan',
        formula: 'O₂N₂C₁₁H₁₂',
        evolvesInto: ['indigo'],
    },
    indigo: {
        name: 'Indigo',
        formula: 'O₂N₂C₁₆H₁₀',
        evolvesInto: [],
    },
    sulfamethoxazole: {
        name: 'Sulfamethoxazole',
        formula: 'SO₃N₃C₁₀H₁₁',
        evolvesInto: [],
    },
    thalidomide: {
        name: 'Thalidomide',
        formula: 'O₄N₂C₁₃H₁₀',
        evolvesInto: [],
    },
    minoxidil: {
        name: 'Minoxidil',
        formula: 'ON₅C₉H₁₅',
        evolvesInto: [],
    },
    menthol: {
        name: 'Menthol',
        formula: 'OC₁₀H₂₀',
        evolvesInto: [],
    },
    deet: {
        name: 'DEET',
        formula: 'ONC₁₂H₁₇',
        evolvesInto: [],
    },
    biotin: {
        name: 'Biotin',
        formula: 'SO₃N₂C₁₀H₁₆',
        evolvesInto: [],
    },
    ibuprofen: {
        name: 'Ibuprofen',
        formula: 'O₂C₁₃H₁₈',
        evolvesInto: [],
    },
    diazepam: {
        name: 'Diazepam',
        formula: 'ClON₂C₁₆H₁₃',
        evolvesInto: [],
    },
    geosmin: {
        name: 'Geosmin',
        formula: 'OC₁₂H₂₂',
        evolvesInto: [],
    },
    famotidine: {
        name: 'Famotidine',
        formula: 'S₃O₂N₇C₈H₁₅',
        evolvesInto: [],
    },
    thiamine: {
        name: 'Thiamine',
        formula: 'SON₄C₁₂H₁₇',
        evolvesInto: [],
    },
    'aflatoxin-b1': {
        name: 'Aflatoxin B1',
        formula: 'O₆C₁₇H₁₂',
        evolvesInto: [],
    },
    sertraline: {
        name: 'Sertraline',
        formula: 'Cl₂NC₁₇H₁₇',
        evolvesInto: [],
    },
    malathion: {
        name: 'Malathion',
        formula: 'S₂PO₆C₁₀H₁₉',
        evolvesInto: [],
    },
    albuterol: {
        name: 'Albuterol',
        formula: 'O₃NC₁₃H₂₁',
        evolvesInto: [],
    },
    lidocaine: {
        name: 'Lidocaine',
        formula: 'ON₂C₁₄H₂₂',
        evolvesInto: [],
    },
    tetrodotoxin: {
        name: 'Tetrodotoxin',
        formula: 'O₈N₃C₁₁H₁₇',
        evolvesInto: [],
    },
    fluoxetine: {
        name: 'Fluoxetine',
        formula: 'F₃ONC₁₇H₁₈',
        evolvesInto: [],
    },
    morphine: {
        name: 'Morphine',
        formula: 'O₃NC₁₇H₁₉',
        evolvesInto: [],
    },
    'penicillin-g': {
        name: 'Penicillin G',
        formula: 'SO₄N₂C₁₆H₁₈',
        evolvesInto: [],
    },
    sucralose: {
        name: 'Sucralose',
        formula: 'Cl₃O₈C₁₂H₁₉',
        evolvesInto: [],
    },
    artemisinin: {
        name: 'Artemisinin',
        formula: 'O₅C₁₅H₂₂',
        evolvesInto: [],
    },
    ciprofloxacin: {
        name: 'Ciprofloxacin',
        formula: 'FO₃N₃C₁₇H₁₈',
        evolvesInto: [],
    },
    omeprazole: {
        name: 'Omeprazole',
        formula: 'SO₃N₃C₁₇H₁₉',
        evolvesInto: [],
    },
    amoxicillin: {
        name: 'Amoxicillin',
        formula: 'SO₅N₃C₁₆H₁₉',
        evolvesInto: [],
    },
    oseltamivir: {
        name: 'Oseltamivir',
        formula: 'O₄N₂C₁₆H₂₈',
        evolvesInto: [],
    },
    'folic-acid': {
        name: 'Folic Acid',
        formula: 'O₆N₇C₁₉H₁₉',
        evolvesInto: [],
    },
    cortisol: {
        name: 'Cortisol',
        formula: 'O₅C₂₁H₃₀',
        evolvesInto: [],
    },
    tetracycline: {
        name: 'Tetracycline',
        formula: 'O₈N₂C₂₂H₂₄',
        evolvesInto: [],
    },
    'beta-carotene': {
        name: 'Beta-Carotene',
        formula: 'C₄₀H₅₆',
        evolvesInto: [],
    },
};

export const moleculeRouteNames = getObjectTypedKeys(moleculeSummaries);
