// cspell:disable
import {getObjectTypedKeys} from '@augment-vir/common';

/**
 * Generated by `npm run init` from the files in `./molecules/`. Do not edit by hand.
 *
 * Display order: fewest atoms first, ties broken by total bond order, then by route name.
 */
export const moleculeSummaries: Readonly<
    Record<string, Readonly<{name: string; formula: string}>>
> = {
    bromine: {
        name: 'Bromine',
        formula: 'Br₂',
    },
    chlorine: {
        name: 'Chlorine',
        formula: 'Cl₂',
    },
    hydrogen: {
        name: 'Hydrogen',
        formula: 'H₂',
    },
    'hydrogen-chloride': {
        name: 'Hydrogen Chloride',
        formula: 'HCl',
    },
    'hydrogen-fluoride': {
        name: 'Hydrogen Fluoride',
        formula: 'FH',
    },
    iodine: {
        name: 'Iodine',
        formula: 'I₂',
    },
    oxygen: {
        name: 'Oxygen',
        formula: 'O₂',
    },
    'carbon-monoxide': {
        name: 'Carbon Monoxide',
        formula: 'CO',
    },
    nitrogen: {
        name: 'Nitrogen',
        formula: 'N₂',
    },
    'hydrogen-sulfide': {
        name: 'Hydrogen Sulfide',
        formula: 'SH₂',
    },
    'hypochlorous-acid': {
        name: 'Hypochlorous Acid',
        formula: 'ClOH',
    },
    water: {
        name: 'Water',
        formula: 'H₂O',
    },
    'xenon-difluoride': {
        name: 'Xenon Difluoride',
        formula: 'XeF₂',
    },
    ozone: {
        name: 'Ozone',
        formula: 'O₃',
    },
    'carbon-dioxide': {
        name: 'Carbon Dioxide',
        formula: 'CO₂',
    },
    'hydrogen-cyanide': {
        name: 'Hydrogen Cyanide',
        formula: 'NCH',
    },
    'nitrous-oxide': {
        name: 'Nitrous Oxide',
        formula: 'ON₂',
    },
    'sulfur-dioxide': {
        name: 'Sulfur Dioxide',
        formula: 'SO₂',
    },
    ammonia: {
        name: 'Ammonia',
        formula: 'NH₃',
    },
    'boron-trifluoride': {
        name: 'Boron Trifluoride',
        formula: 'BF₃',
    },
    'hydrogen-peroxide': {
        name: 'Hydrogen Peroxide',
        formula: 'H₂O₂',
    },
    'nitrogen-trifluoride': {
        name: 'Nitrogen Trifluoride',
        formula: 'F₃N',
    },
    phosphine: {
        name: 'Phosphine',
        formula: 'PH₃',
    },
    'phosphorus-trichloride': {
        name: 'Phosphorus Trichloride',
        formula: 'Cl₃P',
    },
    formaldehyde: {
        name: 'Formaldehyde',
        formula: 'CH₂O',
    },
    phosgene: {
        name: 'Phosgene',
        formula: 'Cl₂OC',
    },
    'thionyl-chloride': {
        name: 'Thionyl Chloride',
        formula: 'Cl₂SO',
    },
    acetylene: {
        name: 'Acetylene',
        formula: 'C₂H₂',
    },
    'sulfur-trioxide': {
        name: 'Sulfur Trioxide',
        formula: 'SO₃',
    },
    'white-phosphorus': {
        name: 'White Phosphorus',
        formula: 'P₄',
    },
    'carbon-tetrachloride': {
        name: 'Carbon Tetrachloride',
        formula: 'Cl₄C',
    },
    chloroform: {
        name: 'Chloroform',
        formula: 'Cl₃CH',
    },
    dichlorodifluoromethane: {
        name: 'Dichlorodifluoromethane',
        formula: 'Cl₂F₂C',
    },
    hydroxylamine: {
        name: 'Hydroxylamine',
        formula: 'ONH₃',
    },
    iodoform: {
        name: 'Iodoform',
        formula: 'I₃CH',
    },
    methane: {
        name: 'Methane',
        formula: 'CH₄',
    },
    silane: {
        name: 'Silane',
        formula: 'SiH₄',
    },
    'silicon-tetrachloride': {
        name: 'Silicon Tetrachloride',
        formula: 'Cl₄Si',
    },
    tetrafluoromethane: {
        name: 'Tetrafluoromethane',
        formula: 'F₄C',
    },
    'xenon-tetrafluoride': {
        name: 'Xenon Tetrafluoride',
        formula: 'XeF₄',
    },
    'formic-acid': {
        name: 'Formic Acid',
        formula: 'O₂CH₂',
    },
    'nitric-acid': {
        name: 'Nitric Acid',
        formula: 'O₃NH',
    },
    hydrazine: {
        name: 'Hydrazine',
        formula: 'N₂H₄',
    },
    methanol: {
        name: 'Methanol',
        formula: 'OCH₄',
    },
    'phosphorus-pentachloride': {
        name: 'Phosphorus Pentachloride',
        formula: 'PCl₅',
    },
    'carbonic-acid': {
        name: 'Carbonic Acid',
        formula: 'O₃CH₂',
    },
    ethylene: {
        name: 'Ethylene',
        formula: 'C₂H₄',
    },
    tetrafluoroethylene: {
        name: 'Tetrafluoroethylene',
        formula: 'F₄C₂',
    },
    'dinitrogen-tetroxide': {
        name: 'Dinitrogen Tetroxide',
        formula: 'O₄N₂',
    },
    'boric-acid': {
        name: 'Boric Acid',
        formula: 'BO₃H₃',
    },
    'sulfur-hexafluoride': {
        name: 'Sulfur Hexafluoride',
        formula: 'SF₆',
    },
    acetaldehyde: {
        name: 'Acetaldehyde',
        formula: 'OC₂H₄',
    },
    nitromethane: {
        name: 'Nitromethane',
        formula: 'O₂NCH₃',
    },
    'sulfuric-acid': {
        name: 'Sulfuric Acid',
        formula: 'SO₄H₂',
    },
    halothane: {
        name: 'Halothane',
        formula: 'BrClF₃C₂H',
    },
    'acetic-acid': {
        name: 'Acetic Acid',
        formula: 'C₂H₄O₂',
    },
    diborane: {
        name: 'Diborane',
        formula: 'B₂H₆',
    },
    octasulfur: {
        name: 'Octasulfur',
        formula: 'S₈',
    },
    'phosphoric-acid': {
        name: 'Phosphoric Acid',
        formula: 'PO₄H₃',
    },
    urea: {
        name: 'Urea',
        formula: 'ON₂CH₄',
    },
    'sulfamic-acid': {
        name: 'Sulfamic Acid',
        formula: 'SO₃NH₃',
    },
    'dimethyl-sulfide': {
        name: 'Dimethyl Sulfide',
        formula: 'SC₂H₆',
    },
    ethanethiol: {
        name: 'Ethanethiol',
        formula: 'SC₂H₆',
    },
    ethanol: {
        name: 'Ethanol',
        formula: 'C₂H₆O',
    },
    cyclopropane: {
        name: 'Cyclopropane',
        formula: 'C₃H₆',
    },
    'chloral-hydrate': {
        name: 'Chloral Hydrate',
        formula: 'Cl₃O₂C₂H₃',
    },
    'ethylene-glycol': {
        name: 'Ethylene Glycol',
        formula: 'O₂C₂H₆',
    },
    acetone: {
        name: 'Acetone',
        formula: 'OC₃H₆',
    },
    'dimethyl-sulfoxide': {
        name: 'Dimethyl Sulfoxide',
        formula: 'SOC₂H₆',
    },
    glycine: {
        name: 'Glycine',
        formula: 'O₂NC₂H₅',
    },
    cisplatin: {
        name: 'Cisplatin',
        formula: 'PtCl₂N₂H₆',
    },
    propane: {
        name: 'Propane',
        formula: 'C₃H₈',
    },
    'allyl-isothiocyanate': {
        name: 'Allyl Isothiocyanate',
        formula: 'SNC₄H₅',
    },
    'isopropyl-alcohol': {
        name: 'Isopropyl Alcohol',
        formula: 'OC₃H₈',
    },
    'lactic-acid': {
        name: 'Lactic Acid',
        formula: 'O₃C₃H₆',
    },
    benzene: {
        name: 'Benzene',
        formula: 'C₆H₆',
    },
    borazine: {
        name: 'Borazine',
        formula: 'B₃N₃H₆',
    },
    'trichloroisocyanuric-acid': {
        name: 'Trichloroisocyanuric Acid',
        formula: 'Cl₃O₃N₃C₃',
    },
    uracil: {
        name: 'Uracil',
        formula: 'O₂N₂C₄H₄',
    },
    trimethylamine: {
        name: 'Trimethylamine',
        formula: 'NC₃H₉',
    },
    cytosine: {
        name: 'Cytosine',
        formula: 'ON₃C₄H₅',
    },
    purine: {
        name: 'Purine',
        formula: 'N₄C₅H₄',
    },
    butane: {
        name: 'Butane',
        formula: 'C₄H₁₀',
    },
    glycerol: {
        name: 'Glycerol',
        formula: 'O₃C₃H₈',
    },
    cysteine: {
        name: 'Cysteine',
        formula: 'SO₂NC₃H₇',
    },
    taurine: {
        name: 'Taurine',
        formula: 'SO₃NC₂H₇',
    },
    benzaldehyde: {
        name: 'Benzaldehyde',
        formula: 'OC₇H₆',
    },
    niacin: {
        name: 'Niacin',
        formula: 'O₂NC₆H₅',
    },
    'diethyl-ether': {
        name: 'Diethyl Ether',
        formula: 'OC₄H₁₀',
    },
    sevoflurane: {
        name: 'Sevoflurane',
        formula: 'F₇OC₄H₃',
    },
    creatinine: {
        name: 'Creatinine',
        formula: 'ON₃C₄H₇',
    },
    melamine: {
        name: 'Melamine',
        formula: 'N₆C₃H₆',
    },
    thymine: {
        name: 'Thymine',
        formula: 'O₂N₂C₅H₆',
    },
    acesulfame: {
        name: 'Acesulfame',
        formula: 'SO₄NC₄H₅',
    },
    adenine: {
        name: 'Adenine',
        formula: 'N₅C₅H₅',
    },
    gaba: {
        name: 'GABA',
        formula: 'O₂NC₄H₉',
    },
    'salicylic-acid': {
        name: 'Salicylic Acid',
        formula: 'O₃C₇H₆',
    },
    guanine: {
        name: 'Guanine',
        formula: 'ON₅C₅H₅',
    },
    'uric-acid': {
        name: 'Uric Acid',
        formula: 'O₃N₄C₅H₄',
    },
    histamine: {
        name: 'Histamine',
        formula: 'N₃C₅H₉',
    },
    coumarin: {
        name: 'Coumarin',
        formula: 'O₂C₉H₆',
    },
    saccharin: {
        name: 'Saccharin',
        formula: 'SO₃NC₇H₅',
    },
    'isoamyl-mercaptan': {
        name: 'Isoamyl Mercaptan',
        formula: 'SC₅H₁₂',
    },
    creatine: {
        name: 'Creatine',
        formula: 'O₂N₃C₄H₉',
    },
    glyphosate: {
        name: 'Glyphosate',
        formula: 'PO₅NC₃H₈',
    },
    cinnamaldehyde: {
        name: 'Cinnamaldehyde',
        formula: 'OC₉H₈',
    },
    'glutamic-acid': {
        name: 'Glutamic Acid',
        formula: 'O₄NC₅H₉',
    },
    allicin: {
        name: 'Allicin',
        formula: 'S₂OC₆H₁₀',
    },
    'methyl-salicylate': {
        name: 'Methyl Salicylate',
        formula: 'O₃C₈H₈',
    },
    vanillin: {
        name: 'Vanillin',
        formula: 'O₃C₈H₈',
    },
    ninhydrin: {
        name: 'Ninhydrin',
        formula: 'O₄C₉H₆',
    },
    methionine: {
        name: 'Methionine',
        formula: 'SO₂NC₅H₁₁',
    },
    ribose: {
        name: 'Ribose',
        formula: 'O₅C₅H₁₀',
    },
    metformin: {
        name: 'Metformin',
        formula: 'N₅C₄H₁₁',
    },
    'ascorbic-acid': {
        name: 'Ascorbic Acid',
        formula: 'O₆C₆H₈',
    },
    nitroglycerin: {
        name: 'Nitroglycerin',
        formula: 'O₉N₃C₃H₅',
    },
    acetaminophen: {
        name: 'Acetaminophen',
        formula: 'O₂NC₈H₉',
    },
    'citric-acid': {
        name: 'Citric Acid',
        formula: 'O₇C₆H₈',
    },
    aspirin: {
        name: 'Aspirin',
        formula: 'C₉H₈O₄',
    },
    theobromine: {
        name: 'Theobromine',
        formula: 'O₂N₄C₇H₈',
    },
    theophylline: {
        name: 'Theophylline',
        formula: 'O₂N₄C₇H₈',
    },
    tnt: {
        name: 'TNT',
        formula: 'O₆N₃C₇H₅',
    },
    methenamine: {
        name: 'Methenamine',
        formula: 'N₄C₆H₁₂',
    },
    dopamine: {
        name: 'Dopamine',
        formula: 'O₂NC₈H₁₁',
    },
    fructose: {
        name: 'Fructose',
        formula: 'O₆C₆H₁₂',
    },
    glucose: {
        name: 'Glucose',
        formula: 'C₆H₁₂O₆',
    },
    caffeine: {
        name: 'Caffeine',
        formula: 'C₈H₁₀N₄O₂',
    },
    triclosan: {
        name: 'Triclosan',
        formula: 'Cl₃O₂C₁₂H₇',
    },
    carvone: {
        name: 'Carvone',
        formula: 'OC₁₀H₁₄',
    },
    serotonin: {
        name: 'Serotonin',
        formula: 'ON₂C₁₀H₁₂',
    },
    hydrochlorothiazide: {
        name: 'Hydrochlorothiazide',
        formula: 'ClS₂O₄N₃C₇H₈',
    },
    acetylcholine: {
        name: 'Acetylcholine',
        formula: 'O₂NC₇H₁₆',
    },
    pfoa: {
        name: 'PFOA',
        formula: 'F₁₅O₂C₈H',
    },
    limonene: {
        name: 'Limonene',
        formula: 'C₁₀H₁₆',
    },
    adrenaline: {
        name: 'Adrenaline',
        formula: 'O₃NC₉H₁₃',
    },
    nicotine: {
        name: 'Nicotine',
        formula: 'N₂C₁₀H₁₄',
    },
    luciferin: {
        name: 'Luciferin',
        formula: 'S₂O₃N₂C₁₁H₈',
    },
    tryptophan: {
        name: 'Tryptophan',
        formula: 'O₂N₂C₁₁H₁₂',
    },
    ddt: {
        name: 'DDT',
        formula: 'Cl₅C₁₄H₉',
    },
    sulfamethoxazole: {
        name: 'Sulfamethoxazole',
        formula: 'SO₃N₃C₁₀H₁₁',
    },
    thalidomide: {
        name: 'Thalidomide',
        formula: 'O₄N₂C₁₃H₁₀',
    },
    minoxidil: {
        name: 'Minoxidil',
        formula: 'ON₅C₉H₁₅',
    },
    indigo: {
        name: 'Indigo',
        formula: 'O₂N₂C₁₆H₁₀',
    },
    menthol: {
        name: 'Menthol',
        formula: 'OC₁₀H₂₀',
    },
    deet: {
        name: 'DEET',
        formula: 'ONC₁₂H₁₇',
    },
    biotin: {
        name: 'Biotin',
        formula: 'SO₃N₂C₁₀H₁₆',
    },
    ibuprofen: {
        name: 'Ibuprofen',
        formula: 'O₂C₁₃H₁₈',
    },
    melatonin: {
        name: 'Melatonin',
        formula: 'O₂N₂C₁₃H₁₆',
    },
    diazepam: {
        name: 'Diazepam',
        formula: 'ClON₂C₁₆H₁₃',
    },
    geosmin: {
        name: 'Geosmin',
        formula: 'OC₁₂H₂₂',
    },
    famotidine: {
        name: 'Famotidine',
        formula: 'S₃O₂N₇C₈H₁₅',
    },
    thiamine: {
        name: 'Thiamine',
        formula: 'SON₄C₁₂H₁₇',
    },
    thyroxine: {
        name: 'Thyroxine',
        formula: 'I₄O₄NC₁₅H₁₁',
    },
    'aflatoxin-b1': {
        name: 'Aflatoxin B1',
        formula: 'O₆C₁₇H₁₂',
    },
    edta: {
        name: 'EDTA',
        formula: 'O₈N₂C₁₀H₁₆',
    },
    sertraline: {
        name: 'Sertraline',
        formula: 'Cl₂NC₁₇H₁₇',
    },
    malathion: {
        name: 'Malathion',
        formula: 'S₂PO₆C₁₀H₁₉',
    },
    albuterol: {
        name: 'Albuterol',
        formula: 'O₃NC₁₃H₂₁',
    },
    lidocaine: {
        name: 'Lidocaine',
        formula: 'ON₂C₁₄H₂₂',
    },
    tetrodotoxin: {
        name: 'Tetrodotoxin',
        formula: 'O₈N₃C₁₁H₁₇',
    },
    aspartame: {
        name: 'Aspartame',
        formula: 'O₅N₂C₁₄H₁₈',
    },
    fluoxetine: {
        name: 'Fluoxetine',
        formula: 'F₃ONC₁₇H₁₈',
    },
    morphine: {
        name: 'Morphine',
        formula: 'O₃NC₁₇H₁₉',
    },
    'penicillin-g': {
        name: 'Penicillin G',
        formula: 'SO₄N₂C₁₆H₁₈',
    },
    '18-crown-6': {
        name: '18-Crown-6',
        formula: 'O₆C₁₂H₂₄',
    },
    sucralose: {
        name: 'Sucralose',
        formula: 'Cl₃O₈C₁₂H₁₉',
    },
    artemisinin: {
        name: 'Artemisinin',
        formula: 'O₅C₁₅H₂₂',
    },
    ciprofloxacin: {
        name: 'Ciprofloxacin',
        formula: 'FO₃N₃C₁₇H₁₈',
    },
    omeprazole: {
        name: 'Omeprazole',
        formula: 'SO₃N₃C₁₇H₁₉',
    },
    amoxicillin: {
        name: 'Amoxicillin',
        formula: 'SO₅N₃C₁₆H₁₉',
    },
    lactose: {
        name: 'Lactose',
        formula: 'O₁₁C₁₂H₂₂',
    },
    sucrose: {
        name: 'Sucrose',
        formula: 'O₁₁C₁₂H₂₂',
    },
    'adenosine-triphosphate': {
        name: 'Adenosine Triphosphate',
        formula: 'P₃O₁₃N₅C₁₀H₁₆',
    },
    riboflavin: {
        name: 'Riboflavin',
        formula: 'O₆N₄C₁₇H₂₀',
    },
    capsaicin: {
        name: 'Capsaicin',
        formula: 'O₃NC₁₈H₂₇',
    },
    oseltamivir: {
        name: 'Oseltamivir',
        formula: 'O₄N₂C₁₆H₂₈',
    },
    'folic-acid': {
        name: 'Folic Acid',
        formula: 'O₆N₇C₁₉H₁₉',
    },
    cortisol: {
        name: 'Cortisol',
        formula: 'O₅C₂₁H₃₀',
    },
    tetracycline: {
        name: 'Tetracycline',
        formula: 'O₈N₂C₂₂H₂₄',
    },
    'beta-carotene': {
        name: 'Beta-Carotene',
        formula: 'C₄₀H₅₆',
    },
};

export const moleculeRouteNames = getObjectTypedKeys(moleculeSummaries);
