// cspell:words Pokédex
import {removeSuffix} from '@augment-vir/common';
import {
    getMoleculeFormula,
    getTotalBondOrder,
    type Molecule,
} from '@molecules/frontend/src/data/molecule.js';
import {readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {format, resolveConfig} from 'prettier';
import {allMoleculesFilePath, moleculesDirPath} from './file-paths.js';

const moleculeFileSuffix = '.molecule.ts';

async function loadMolecule(routeName: string) {
    /**
     * V8 reports the code after this `await import()` as an uncovered branch even though every call
     * reaches it.
     */
    /* c8 ignore next 3 */
    const molecule: Molecule = (
        await import(pathToFileURL(join(moleculesDirPath, routeName + moleculeFileSuffix)).href)
    ).default;
    return {
        routeName,
        molecule,
    };
}

/**
 * Reorders molecules like a Pokédex: each molecule that starts an evolution line is followed by its
 * evolutions, each evolution by its own evolutions, before the next line starts. The input must
 * already be sorted simplest first; that order decides which line comes first and which of a
 * molecule's evolutions comes first.
 *
 * A molecule that more than one molecule evolves into follows whichever of them comes first.
 *
 * @example
 *
 * ```ts
 * orderByEvolutionLine([
 *     {routeName: 'hydrogen', evolvesInto: ['water']},
 *     {
 *         routeName: 'oxygen',
 *         evolvesInto: [
 *             'ozone',
 *             'water',
 *         ],
 *     },
 *     {routeName: 'water', evolvesInto: []},
 *     {routeName: 'ozone', evolvesInto: []},
 * ]).map((entry) => entry.routeName);
 * // ['hydrogen', 'water', 'oxygen', 'ozone']
 * ```
 */
export function orderByEvolutionLine<
    const Entry extends Readonly<{
        routeName: string;
        evolvesInto: ReadonlyArray<string>;
    }>,
>(sortedEntries: ReadonlyArray<Entry>) {
    const evolvedRouteNames = sortedEntries.flatMap((entry) => entry.evolvesInto);

    /** Annotated because the recursion leaves TypeScript nothing to infer from. */
    function addLine(ordered: ReadonlyArray<Entry>, entry: Entry): Entry[] {
        if (ordered.includes(entry)) {
            return [...ordered];
        }

        return sortedEntries
            .filter((evolution) => entry.evolvesInto.includes(evolution.routeName))
            .reduce(addLine, [
                ...ordered,
                entry,
            ]);
    }

    return sortedEntries
        .filter((entry) => !evolvedRouteNames.includes(entry.routeName))
        .reduce<Entry[]>(addLine, []);
}

/**
 * Builds the contents of the frontend's `all-molecules.ts` from every `.molecule.ts` file, with
 * each file's name as its route name, so the frontend can list every molecule's name, formula, and
 * evolutions without loading each molecule file. Ordered by `orderByEvolutionLine`, starting from
 * fewest atoms first, then lowest total bond order, then by route name.
 */
export async function generateAllMoleculesCode() {
    const routeNames = (await readdir(moleculesDirPath))
        .filter((fileName) => fileName.endsWith(moleculeFileSuffix))
        .map((fileName) => {
            return removeSuffix({
                value: fileName,
                suffix: moleculeFileSuffix,
            });
        });
    const sortedMolecules = orderByEvolutionLine(
        (await Promise.all(routeNames.map(loadMolecule)))
            .toSorted((first, second) => {
                return (
                    first.molecule.atoms.length - second.molecule.atoms.length ||
                    getTotalBondOrder(first.molecule.bonds) -
                        getTotalBondOrder(second.molecule.bonds) ||
                    first.routeName.localeCompare(second.routeName)
                );
            })
            .map((entry) => {
                return {
                    ...entry,
                    evolvesInto: (entry.molecule.stats.evolvesInto ?? []).map(
                        (evolution) => evolution.routeName,
                    ),
                };
            }),
    );

    const code = [
        '// cspell:disable',
        "import {getObjectTypedKeys} from '@augment-vir/common';",
        '',
        '/**',
        ' * Generated by `npm run init` from the files in `./molecules/`. Do not edit by hand.',
        ' *',
        ' * Display order: like a Pokédex, each molecule is followed by its evolution line. Molecules',
        ' * that start a line are ordered by fewest atoms first, ties broken by total bond order, then by',
        ' * route name.',
        ' */',
        'export const moleculeSummaries: Readonly<',
        '    Record<string, Readonly<{name: string; formula: string; evolvesInto: string[]}>>',
        '> = {',
        ...sortedMolecules.map(({routeName, molecule, evolvesInto}) => {
            return [
                `${JSON.stringify(routeName)}: {`,
                `name: ${JSON.stringify(molecule.name)},`,
                `formula: ${JSON.stringify(getMoleculeFormula(molecule.atoms))},`,
                `evolvesInto: ${JSON.stringify(evolvesInto)},`,
                '},',
            ].join('\n');
        }),
        '};',
        '',
        'export const moleculeRouteNames = getObjectTypedKeys(moleculeSummaries);',
        '',
    ].join('\n');

    return await format(code, {
        ...(await resolveConfig(allMoleculesFilePath)),
        filepath: allMoleculesFilePath,
    });
}
