import {removeSuffix} from '@augment-vir/common';
import {getTotalBondOrder, type Molecule} from '@molecules/frontend/src/data/molecule.js';
import {readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {format, resolveConfig} from 'prettier';
import {allMoleculesFilePath, moleculesDirPath} from './file-paths.js';

const moleculeFileSuffix = '.molecule.ts';

async function loadMolecule(routeName: string) {
    /**
     * V8 reports the code after this `await import()` as an uncovered branch even though every call
     * reaches it.
     */
    /* c8 ignore next 3 */
    const molecule: Molecule = (
        await import(pathToFileURL(join(moleculesDirPath, routeName + moleculeFileSuffix)).href)
    ).default;
    return {
        routeName,
        molecule,
    };
}

/**
 * Builds the contents of the frontend's `all-molecules.ts` from every `.molecule.ts` file, with
 * each file's name as its route name. Each molecule is loaded to sort them: fewest atoms first,
 * then lowest total bond order, then by route name.
 */
export async function generateAllMoleculesCode() {
    const routeNames = (await readdir(moleculesDirPath))
        .filter((fileName) => fileName.endsWith(moleculeFileSuffix))
        .map((fileName) => {
            return removeSuffix({
                value: fileName,
                suffix: moleculeFileSuffix,
            });
        });
    const sortedRouteNames = (await Promise.all(routeNames.map(loadMolecule)))
        .toSorted((first, second) => {
            return (
                first.molecule.atoms.length - second.molecule.atoms.length ||
                getTotalBondOrder(first.molecule.bonds) -
                    getTotalBondOrder(second.molecule.bonds) ||
                first.routeName.localeCompare(second.routeName)
            );
        })
        .map(({routeName}) => routeName);

    const code = [
        '// cspell:disable',
        '/**',
        ' * Generated by `npm run init` from the files in `./molecules/`. Do not edit by hand.',
        ' *',
        ' * Display order: fewest atoms first, ties broken by total bond order, then by route name.',
        ' */',
        'export const moleculeRouteNames = [',
        ...sortedRouteNames.map((routeName) => `'${routeName}',`),
        '];',
        '',
    ].join('\n');

    return await format(code, {
        ...(await resolveConfig(allMoleculesFilePath)),
        filepath: allMoleculesFilePath,
    });
}
